apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-music
  namespace: default
spec:
  selector:
    matchLabels:
      app: spring-music
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-music
    spec:
      containers:
      - name: spring-music
        image: paastaccc/spring-music-sample:0.1
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 500m
            memory: 200Mi
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-music-service
spec:
  ports:
  ports:
    - port: 8083
      protocol: TCP
      targetPort: 8080
  selector:
    app: spring-music
  type: NodePort
